### ISSUE TITLE
implement website infrastructure

### ISSUE THREAD

**Issue by vilnacrm** [VilnaCRM-Org/website-infrastructure#1]
As a developer, I need to be able to implement, test, and maintain the website in various environments (sandbox, production)

### Tasks

- [x] VilnaCRM-Org/infrastructure-template#1
- [ ] VilnaCRM-Org/infrastructure-template#2
- [ ] VilnaCRM-Org/infrastructure-template#4 

### Acceptance Criteria

- [ ] all tasks finished
