### ISSUE TITLE
set up the frontend production infrastructure

### ISSUE THREAD

**Issue by vilnacrm** [VilnaCRM-Org/website-infrastructure#2]
As a frontend/user, I need to be able to merge pull requests to the main branch and see my features and fixes on the production vilnacrm.com.

### Tasks

- [x] configure Terraform for frontend (Cloudfront, AWS S3)
- [x] [implement CD for terraform pipeline](https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/create-a-ci-cd-pipeline-to-validate-terraform-configurations-by-using-aws-codepipeline.html) (execute terraspace up when PR've merged to the main branch)
- [x] add automatically roles, and permissions using Terraform
- [x] configure [GitHub Actions](https://github.com/VilnaCRM-Org/website/blob/main/.github/workflows/deploy-prod.yml) to deploy production (replace this implementation with the AWS CodeBuild approach to be more secure) 
- [x] create health checks for deploying production
- [x] configure logs, monitoring, and alerting for frontend through AWS CloudWatch
- [x] configure alerting channels in Slack (sentry, cloud watch, uptime robot)
- [x] set up blue/green releases for the frontend production deployments
- [x] add [diagrams](https://diagrams.mingrammer.com)

### Acceptance Criteria

- [ ] new features deployed to the production after merging pull requests to the main branch
- [x] health checks works
- [x] all teams can see logs and monitoring information
- [x] alerts works and writes to the slack
- [x] production deploying according to the rules of the blue/green release
- [x] rollback is working for production
- [x] all infrastructure CI checks passed

**Comment by YapieRT** [comment]
- [ ] Rework Validation
- [ ] Rework hurl
- [ ] Move Versions in Buildspecs to one file
- [ ] Duplicate external S3 module into repository
- [ ] Remove S3 lifecycle configuration and suppress error CKV2_AWS_61
- [ ] Ignore KMS S3 CKV_AWS_145
- [ ] Integrate S3 CKV_AWS_144
- [ ] Integrate S3 CKV_AWS_18
- [ ] Integrate S3 CKV2_AWS_32
- [ ] Integrate S3 CKV2_AWS_62 and implement into ChatBot security channel and only when it`s not new version (Object removed and ObjectAcl)
- [ ] Integrate Cloudfront CKV2_AWS_47
- [ ] Integrage Cloudfront CKV_AWS_310
- [ ] Integrage Cloudfront CKV_AWS_86
- [ ] Integrage Cloudfront CKV_AWS_68

**Comment by YapieRT** [comment]
- [ ] Least privelege for all created roles and permissions using Access Advisor.

~ 3 days

- [ ] Remove tokens from secrets manager and create for it separate user for deployment.

  - Auto-rotation enabled.
  - Delete terraform user.
  - Use iamlive for scanning.
  - Use AWS session or AWS STS.

~ 5 days

- [ ] First - deployment users and for different stack - different users(codepipeline and website) in these stacks.

~ 8 days

- [ ] Create auto system for iamlive.\*\* Needs IAM user that can change role`s policies and only this.

~ 4 days
