### ISSUE TITLE
set up a frontend sandbox infrastructure

### ISSUE THREAD

**Issue by vilnacrm** [VilnaCRM-Org/website-infrastructure#3]
As a front-end developer, I need to be able to create pull requests to the main branch and see my new features and fixes on the sandbox environment.

### Tasks

- [ ] configure Terraform for frontend (AWS CloudFront, AWS S3)
- [ ] configure GitHub Actions to deploy and destroy sandbox
- [ ] configure Terraform, and Ansible to deploy and destroy sandboxes
- [ ] create health checks for deploying sandboxes
- [ ] configure logs, monitoring, and alerting for frontend through AWS CloudWatch (Maybe: ELK, Prometheus, Grafana)
- [ ] configure alerting channels in Slack (sentry, cloud watch, uptime robot)

### Acceptance Criteria

- [ ] new features deployed to the sandbox after creating pull requests to the main branch
- [ ] health checks works
- [ ] all teams can see logs and monitoring information
- [ ] alerts works and writes to the slack
- [ ] all infrastructure tests passed
